name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - run: go test --race -v ./...

  fuzz:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fuzz: [ FuzzMarshalUnmarshalRoundtrip, FuzzPointerRoundtrip, FuzzAccessAsValueAndAsValue ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - run: go test --race --fuzz ${{ matrix.fuzz }} -fuzztime 60s
